// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6NnZTO1f4e7f-x9o6yuqydBVsxq9M0Y',
    appId: '1:503876111267:web:d627f9ff97cea9172fa816',
    messagingSenderId: '503876111267',
    projectId: 'magic-collection-project',
    authDomain: 'magic-collection-project.firebaseapp.com',
    storageBucket: 'magic-collection-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEABp399r3TEZUJ8dx23i4dDGusR4ylA',
    appId: '1:503876111267:android:ff60d745e2ff87432fa816',
    messagingSenderId: '503876111267',
    projectId: 'magic-collection-project',
    storageBucket: 'magic-collection-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKjG1Sj9mU1Rk2j_WDIUen-XoY-GOnEA',
    appId: '1:503876111267:ios:94398cc07cd819052fa816',
    messagingSenderId: '503876111267',
    projectId: 'magic-collection-project',
    storageBucket: 'magic-collection-project.firebasestorage.app',
    iosBundleId: 'com.magic.collection.magicCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKjG1Sj9mU1Rk2j_WDIUen-XoY-GOnEA',
    appId: '1:503876111267:ios:94398cc07cd819052fa816',
    messagingSenderId: '503876111267',
    projectId: 'magic-collection-project',
    storageBucket: 'magic-collection-project.firebasestorage.app',
    iosBundleId: 'com.magic.collection.magicCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl6NnZTO1f4e7f-x9o6yuqydBVsxq9M0Y',
    appId: '1:503876111267:web:a762206bb8883ecb2fa816',
    messagingSenderId: '503876111267',
    projectId: 'magic-collection-project',
    authDomain: 'magic-collection-project.firebaseapp.com',
    storageBucket: 'magic-collection-project.firebasestorage.app',
  );
}
